name: Subs Check

on:
  schedule:
    - cron: '0 0,4,8,12,16 * * *'
  workflow_dispatch:

jobs:
  run-subs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run subs-check once
        run: |
          go run ./cmd/once/once.go -f ./config/config.yaml

      - name: Commit and Push output
        run: |
          mkdir -p output
          cp -r /tmp/go-build*/b001/exe/output/* ./output/
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add output
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update output [auto]"
            git pull --rebase origin master
            git push origin HEAD:master
          fi
