name: Subs Check

on:
  schedule:
    - cron: '0 0,4,8,12,16 * * *'  # 每天 UTC 02:00 执行（可根据需要修改）
  workflow_dispatch:      # 允许手动触发

jobs:
  run-subs-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run subs-check
        run: |
          mkdir -p output
          go run . -f ./config/config.yaml

      - name: Commit and Push output
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add output
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update output [auto]"
            git pull --rebase origin master  # 如果你的主分支是 main 就改成 main
            git push origin HEAD:master      # 如果你的主分支是 main 就改成 main
          fi
