name: Subs Check

on:
  schedule:
    - cron: '0 0,4,8,12,16 * * *'
  workflow_dispatch:

jobs:
  run-subs-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Run subs-check once
        run: |
          go build -o ./bin/subs-check ./cmd/once/once.go  
          ./bin/subs-check -f ./config/config.yaml

      - name: Debug /tmp content
        run: |
            ls ./
      #     ls -l /tmp
      #     ls -l /tmp/go-build*
      #     ls -l /tmp/go-build*/b001/exe/output

      - name: Commit and Push output
        run: |
          # tmpdir=$(ls -d /tmp/go-build*/b001/exe/output)
          # echo "临时目录是 $tmpdir"
          # mkdir -p output
          # cp -r "$tmpdir"/* ./output/
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add output
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update output [auto]"
            git pull --rebase origin master
            git push origin HEAD:master
          fi
